I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/tablet_data_email.rpy", line 6, in script
    init python:
  File "game/tablet_data_email.rpy", line 7, in <module>
    renpy.watch("TAB_EMAIL_READ")
  File "renpy/common/00console.rpy", line 617, in renpy_watch
    watch(l)
  File "renpy/common/00console.rpy", line 601, in watch
    traced_expressions.append(expr)
NameError: global name 'traced_expressions' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/tablet_data_email.rpy", line 6, in script
    init python:
  File "C:\Software\RenPy\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Software\RenPy\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/tablet_data_email.rpy", line 7, in <module>
    renpy.watch("TAB_EMAIL_READ")
  File "renpy/common/00console.rpy", line 617, in renpy_watch
    watch(l)
  File "renpy/common/00console.rpy", line 601, in watch
    traced_expressions.append(expr)
NameError: global name 'traced_expressions' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Limbus inc. 1.0
Sat Aug 08 09:21:14 2020
